version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          key: project-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Unit tests
          command: cargo test --release
      - save_cache:
          name: Cache dependencies
          key: project-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "target/release/deps"
            - "target/release/.fingerprint"
            - "target/release/build"
      - setup_remote_docker
      - run:
          name: Download tests
          command: |
            set -x -e
            cd util
            make -C serve
            ./run_tests.sh
      - run:
          name: Prepare release binary
          command: |
            strip target/release/tempget
      - store_artifacts:
          path: "target/release/tempget"
