version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          key: project-cache
      - run:
          name: Build
          command: cargo build
      - run:
          name: Unit tests
          command: cargo test
      - setup_remote_docker
      - run:
          name: Download tests
          command: |
            set -x -e
            cd util
            make -C serve
            docker-compose up -d
            ./run_tests.sh
      - save_cache:
          name: Cache dependencies
          key: project-cache
          paths:
            - "~/.cargo"
            - ".target"
