version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          key: project-cache
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Unit tests
          command: cargo test --release
      - save_cache:
          name: Cache dependencies
          key: project-cache
          paths:
            - "~/.cargo"
            - "target"
      - setup_remote_docker
      - run:
          name: Download tests
          command: |
            set -x -e
            cd util
            make -C serve
            ./run_tests.sh
      - store_artifacts:
          path: "target/release/tempget"
